from textwrap import dedent
from crewai import Crew, Task, Agent

# Define agents
idea_analyst = Agent(
    role="Idea Analyst",
    goal="Generate key points about Crew AI",
    backstory="An expert in AI technologies and frameworks",
    verbose=True
)

writer = Agent(
    role="Writer",
    goal="Write a compelling paragraph about Crew AI based on key points",
    backstory="A professional content writer with experience in technology and AI",
    verbose=True
)

editor = Agent(
    role="Editor",
    goal="Edit the written paragraph for clarity and coherence",
    backstory="An experienced editor with a keen eye for detail",
    verbose=True
)

# Define tasks
class CreateTasks:
    def __init__(self, topic):
        self._topic = topic

    def expand_idea(self):
        return dedent(f"""
            Analyse the given topic {self._topic}. Prepare comprehensive key points about {self._topic}, 
            including its features, benefits, and use cases. 
            Make sure the ideas are to the point, coherent, and compelling.
        """)


    def write(self):
        return dedent(f"""
            Write a compelling paragraph based on the key points generated by the Idea Analyst 
            about {self._topic}. Ensure the content is clear, concise, and engaging.
        """)

    def edit(self):
        return dedent(f"""
            Review the written paragraph for any grammatical mistakes, improve clarity, redability and flow. 
            Ensure the final text is polished and professional.
        """)

# Create a content writing crew
class ContentWritingCrew:
    def __init__(self, topic):
        self.topic = topic

    def __call__(self):
        tasks = self._create_tasks()
        crew = Crew(
            tasks=tasks,
            agents=[idea_analyst, writer, editor],
            verbose=True
        )
        result = crew.kickoff()
        return result

    def _create_tasks(self):
        create_task = CreateTasks(self.topic)
        expand_idea_task = Task(
            description=create_task.expand_idea(),
            expected_output=f"List of key points about {self.topic}",
            agent=idea_analyst
        )
        write_task = Task(
            description=create_task.write(),
            agent=writer,
            expected_output=f"A well-written paragraph about {self.topic}"
        )
        edit_task = Task(
            description=create_task.edit(),
            agent=editor,
            expected_output=f"Edited and polished paragraph about {self.topic}"
        )
        return [expand_idea_task, write_task, edit_task]


topic = "Crew AI"
my_crew = ContentWritingCrew(topic=topic)
result = my_crew()
print(dedent(result))
